package Assignment;

import java.util.Random;

public class GeneratedByStrongPassword {
public static void main(String[] args) {
	String Uppercase="ABCDEFGHIJKLMNOPQRSTUVWXYZ";
	String Lowercase="abcdefghijklmnopqrstuvwxyz";
	String Numbers="0123456789";
	String Specialcharacters="(!@#$&%^),./||{+-?}[]";
	String Combinating=Uppercase+Lowercase+Numbers+Specialcharacters;
	int len=8;
	char [] Password=new char[len];
	Random r=new Random();
	for(int i=0;i<len;i++) {
		Password[i]=Combinating.charAt(r.nextInt(Combinating.length()));
	}
	System.out.println("Generated By Strong Password="+new String(Password));
}
}
